/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ndkapplication_patchdemo_PathUtils */

#ifndef _Included_ndkapplication_patchdemo_PathUtils
#define _Included_ndkapplication_patchdemo_PathUtils
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ndkapplication_patchdemo_PathUtils
 * Method:    combine
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_ndkapplication_patchdemo_PathUtils_combine
  (JNIEnv *, jclass, jstring, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
