/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class net_bither_util_Test */


#ifdef __cplusplus
extern "C" {
#endif
JNIEXPORT jint JNICALL Java_com_demo_ndk_MainActivity_compressBitmap(JNIEnv*,
		jclass, jobject , int , jstring);

#ifdef __cplusplus
}
#endif

